version: '3.7'

services:
#    llama-cpp-python:
#        image: 3x3cut0r/llama-cpp-python:latest
#        container_name: llama-cpp-python-jarvis
#        cap_add:
#            - SYS_RESOURCE
#        environment:
#            MODEL_DOWNLOAD: "True" 
#            MODEL_REPO: "cfahlgren1/natural-functions-GGUF" 
#            MODEL: "natural-functions.Q6_K.gguf" 
#            MODEL_ALIAS: "natural-functions" 
#            DEFAULT_MODEL: "natural-functions.Q6_K.gguf" 
#            N_GPU_LAYERS : 32
#            N_CTX : 4096
#        volumes:
#            - ./model:/model
#        ports:
#            - '8000:8000'

    ollama:
        image: ollama/ollama
        container_name: ollama
        ports:
        - 8085:11434
        volumes:
        - ./models:/root/.ollama/models
        environment:
            OLLAMA_ORIGINS: '*' 
            #OLLAMA_HOST: "localhost:11434"
            #OLLAMA_PORT: 11434  
        deploy:
            resources:
                reservations:
                    devices:
                        - driver: nvidia
                          #device_ids: ['0']
                          count: 1
                          capabilities: [gpu]
        #command: "ollama pull calebfahlgren/natural-functions"                  
        command: 
            - "serve"

    mariadb:
        image: mariadb:10.6.4-focal
        volumes:
            - type: volume
              source: dbdata
              target: /var/lib/mysql
        environment:
            TZ: 'Europe/Rome'
            MYSQL_ALLOW_EMPTY_PASSWORD: 'no'
            MYSQL_ROOT_PASSWORD: '${MYSQL_ROOT_PASSWORD}'
            MYSQL_USER: '${MYSQL_USER}'
            MYSQL_PASSWORD: '${MYSQL_PASSWORD}'
            MYSQL_DATABASE: '${MYSQL_DATABASE}'
    adminer:
        image: adminer
        restart: always
        ports:
        - 8081:8080

    php-apache:
        build:
            context: .
        environment:
            APIKEY: ${APIKEY}
            MODEL: ${MODEL}
            MAIL_HOST: ${MAIL_HOST}
            MAIL_PORT: ${MAIL_PORT}
            MAIL_FROM: ${MAIL_FROM}
            MAIL_USERNAME: ${MAIL_USERNAME}
            MAIL_PASSWORD: ${MAIL_PASSWORD}
            PORTAINER_URL: ${PORTAINER_URL}
            PORTAINER_USERNAME: ${PORTAINER_USERNAME}
            PORTAINER_PASSWORD: ${PORTAINER_PASSWORD}
        volumes:
            #- type: bind
            #  source: ai_content
            #  target: /usr/src/app/ai_content
            #- type: volume
            #  source: uploads
            #  target: /usr/src/app/public/uploads
            - ./src/app:/usr/src/app

        ports:
            - '8080:80'
volumes:
    ai_content:
    uploads:
    dbdata:
    ollama:

